# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "main"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-servlet"
        versions: [ "[10.0,)" ]
      - dependency-name: "org.slf4j:slf4j-api"
        versions: [ "[2.0,)" ]
      - dependency-name: "ch.qos.logback:logback-classic"
        versions: [ "[1.3,)" ]
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "5.x.x-stable"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-servlet"
        versions: ["[10.0,)"]
      - dependency-name: "org.slf4j:slf4j-api"
        versions: [ "[2.0,)" ]
      - dependency-name: "ch.qos.logback:logback-classic"
        versions: [ "[1.3,)" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "5.x.x-stable"
