name: Test against RabbitMQ 3.11 alpha

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  RABBITMQ_IMAGE_TAG: 3.11
  RABBITMQ_IMAGE: rabbitmq

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Checkout tls-gen
        uses: actions/checkout@v3
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Checkout GraalVM test project
        uses: actions/checkout@v3
        with:
          repository: rabbitmq/rabbitmq-graal-vm-test
          path: './rabbitmq-graal-vm-test'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
      - name: Start broker
        run: ci/start-broker.sh
      - name: Get dependencies
        run: make deps
      - name: Install client JAR file
        run: |
          ./mvnw clean install -Psnapshots -DskipITs -DskipTests --no-transfer-progress
          export ARTEFACT_VERSION=$(cat pom.xml | grep -oPm1 "(?<=<version>)[^<]+")
          echo "artefact_version=$ARTEFACT_VERSION" >> $GITHUB_ENV
      - name: Package test application
        working-directory: rabbitmq-graal-vm-test
        run: |
          ./mvnw --version
          echo "Using RabbitMQ Java Client ${{ env.artefact_version }}"
          ./mvnw -q clean package -Damqp-client.version=${{ env.artefact_version }}
      - name: Start one-time RPC server
        working-directory: rabbitmq-graal-vm-test
        run: ./mvnw -q compile exec:java -Damqp-client.version=${{ env.artefact_version }} &
      - name: Create native image
        working-directory: rabbitmq-graal-vm-test
        run: |
          native-image -jar target/rabbitmq-graal-vm-test-full.jar \
            --initialize-at-build-time=com.rabbitmq.client \
            --initialize-at-build-time=org.slf4j --no-fallback
      - name: Use native image program
        working-directory: rabbitmq-graal-vm-test
        run: ./rabbitmq-graal-vm-test-full
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq